services:
  meterreadings:
    image: ${DOCKER_REGISTRY-}meterreadings
    build:
      context: .
      dockerfile: MeterReadings/Dockerfile
    depends_on:
        - sqlserver

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    hostname: sqlserverdocker
    ports:
     - 1433:1433
    environment:
      - SA_PASSWORD=myP@ssword1234
      - ACCEPT_EULA=Y
